/* eslint-disable react/jsx-key */
/* eslint-disable @next/next/no-img-element */
/* eslint-disable jsx-a11y/alt-text */
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../../styles/Home.module.css';

export default function MovieItem({ info }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Filme: {info.title} </h1>

        <p>
          <b>Nota:</b> {info.vote_average}
        </p>
        <p> {info.overview} </p>

        <img
          src={`https://image.tmdb.org/t/p/original/${info.backdrop_path}`}
          width='400'
        />

        <hr />
        <Link href='/'>Tela inicial</Link>
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const movieId = context.params.id;
  const res = await fetch(`http://localhost:3000/api/movie/${movieId}`);
  const json = await res.json();

  console.log('  getServerSideProps', json.info.title);
  return {
    props: {
      info: json.info,
    },
  };
}
