/* eslint-disable react/jsx-key */
/* eslint-disable @next/next/no-img-element */
/* eslint-disable jsx-a11y/alt-text */
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import { useState } from 'react';

export default function Home({ list }) {
  const [searchText, setSearchText] = useState('');
  const [movieList, setMovieList] = useState([]);

  const handleSearch = async () => {
    if (searchText != '') {
      const result = await fetch(
        `http://localhost:3000/api/search?q=${searchText}`
      );
      const json = await result.json();

      console.log('retornou da busca => ', json.list);

      setMovieList(json.list);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Estudando next</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Busca</h1>
        <input
          type='text '
          value={searchText}
          onChange={(e) => setSearchText(e.target.value)}
        />
        <button onClick={handleSearch}> Buscar</button>

        <hr />

        <ul>
          {movieList.map((item) => (
            <li key={item.id}>
              <a href={`/movie/${item.id}`}>
                <img
                  src={`https://image.tmdb.org/t/p/original${item.poster_path}`}
                  width='150'
                />
                <br />
                {item.title}
              </a>
            </li>
          ))}
        </ul>
        <hr />
        <Link href='/'>Tela inicial</Link>
      </main>
    </div>
  );
}
